const input = [
'posh crimson  contain 2 mirrored tan , 1 faded red , 1 striped gray ',
'bright gray  contain 1 striped white , 4 vibrant cyan , 4 clear white , 4 muted gold ',
'pale plum  contain 1 dark silver ',
'light tomato  contain 5 plaid brown , 5 bright maroon , 5 shiny beige ',
'wavy brown  contain 2 faded lavender , 2 wavy coral , 5 clear gold ',
'dark chartreuse  contain 4 striped lavender , 2 shiny silver , 5 wavy plum ',
'dotted chartreuse  contain 3 shiny teal , 4 posh maroon ',
'muted purple  contain 2 pale lavender , 5 drab red , 3 wavy fuchsia ',
'shiny gray  contain 5 pale red , 1 light chartreuse , 5 bright blue , 3 light gold ',
'dull cyan  contain 2 light green , 2 vibrant fuchsia ',
'dotted gray  contain 4 light bronze , 5 dim blue ',
'muted plum  contain 3 shiny brown , 4 shiny teal ',
'bright magenta  contain 1 plaid yellow , 1 dull white ',
'dotted lime  contain 4 shiny gray , 2 bright teal , 5 dim fuchsia , 1 vibrant chartreuse ',
'mirrored beige  contain 2 plaid crimson , 3 wavy tomato ',
'pale purple  contain 2 faded chartreuse , 2 dark lime , 4 drab white , 4 shiny olive ',
'dull bronze  contain 3 bright lavender ',
'striped bronze  contain 1 dark olive , 5 dotted orange ',
'vibrant orange  contain 1 plaid plum , 1 faded lime , 1 clear lavender , 1 muted brown ',
'dull blue  contain 5 dotted tan , 2 light crimson ',
'mirrored red  contain 1 shiny crimson ',
'vibrant coral  contain 1 vibrant gray ',
'plaid tan  contain 4 clear magenta , 5 posh brown , 5 drab lime ',
'dark yellow  contain 2 striped bronze , 3 shiny tomato ',
'mirrored lime  contain 3 bright orange ',
'mirrored salmon  contain 3 dark white , 5 clear salmon ',
'light crimson  contain 1 plaid cyan , 2 pale silver , 5 pale violet , 1 shiny crimson ',
'clear white  contain 2 muted blue , 5 dotted olive ',
'muted magenta  contain 4 dark purple ',
'clear red  contain 4 dark gray , 3 striped beige ',
'plaid gray  contain 3 faded olive ',
'posh teal  contain 3 pale gray , 3 dim beige , 2 dark gray , 1 shiny coral ',
'pale violet  contain 5 pale silver , 2 shiny crimson , 5 dull olive , 2 drab magenta ',
'shiny purple  contain 5 shiny indigo , 3 dotted green , 2 wavy blue , 3 light salmon ',
'mirrored gold  contain 2 muted coral , 4 shiny lavender ',
'drab brown  contain 1 posh lime ',
'dull salmon  contain 5 dotted lavender , 3 plaid gray , 5 dim coral ',
'striped coral  contain 5 muted brown , 3 muted plum , 2 dim aqua ',
'dark violet  contain 5 drab chartreuse ',
'dark lavender  contain 3 posh lime ',
'plaid fuchsia  contain no other ',
'faded yellow  contain 3 posh lime , 4 wavy blue , 3 faded crimson , 2 shiny lavender ',
'faded crimson  contain 2 dim yellow , 5 drab chartreuse ',
'dull red  contain 3 dark silver , 5 faded plum ',
'dull lime  contain 1 dim black ',
'vibrant tomato  contain 3 dull gray ',
'light tan  contain 3 dim brown , 5 striped lavender , 2 dull indigo ',
'pale turquoise  contain 4 posh plum , 5 striped chartreuse , 5 dim magenta ',
'dim gray  contain 2 mirrored indigo , 3 dim white ',
'bright salmon  contain 5 bright lavender ',
'faded coral  contain 5 striped blue , 3 dark plum , 3 mirrored blue ',
'mirrored bronze  contain 3 dark gold , 1 faded teal ',
'bright aqua  contain 2 vibrant olive ',
'wavy purple  contain 3 wavy teal , 5 dim olive , 3 muted blue ',
'bright crimson  contain 5 drab blue ',
'bright white  contain 2 light cyan , 1 posh silver ',
'striped turquoise  contain 5 mirrored gray ',
'drab magenta  contain 4 vibrant green , 3 mirrored black , 4 muted white ',
'clear teal  contain 1 wavy bronze , 5 dark turquoise , 2 drab teal ',
'dull aqua  contain 4 dim fuchsia , 3 drab green , 3 muted tomato ',
'posh coral  contain 4 wavy bronze , 4 mirrored blue , 2 pale white , 3 shiny brown ',
'faded olive  contain 1 muted brown ',
'muted white  contain 1 vibrant green ',
'plaid violet  contain 5 drab magenta ',
'clear cyan  contain 1 clear gray , 1 mirrored gold , 4 mirrored white , 5 clear brown ',
'dull coral  contain 3 bright blue , 1 light plum , 4 dotted violet , 1 dim teal ',
'plaid blue  contain 3 dark plum , 1 wavy aqua , 1 plaid turquoise ',
'posh indigo  contain 4 dim black , 5 posh orange ',
'drab plum  contain 1 bright tan , 3 faded bronze , 5 plaid bronze ',
'mirrored aqua  contain 2 striped coral ',
'posh salmon  contain 1 mirrored tomato , 2 shiny red ',
'pale yellow  contain 5 striped fuchsia , 3 muted gray , 3 plaid green ',
'faded purple  contain 5 mirrored tan , 2 faded lime ',
'faded blue  contain 4 bright green , 5 dark crimson ',
'dark beige  contain 3 pale magenta , 4 vibrant lavender , 4 posh aqua , 3 striped fuchsia ',
'bright cyan  contain 3 pale violet , 5 pale coral , 4 shiny black , 1 dark blue ',
'wavy green  contain 1 dotted purple , 4 muted gold ',
'pale orange  contain 1 drab tomato , 3 muted purple , 3 muted coral ',
'vibrant violet  contain 1 wavy olive , 2 plaid chartreuse , 5 light cyan ',
'vibrant plum  contain 5 light olive ',
'shiny silver  contain 1 faded coral , 2 dotted olive , 4 mirrored red , 3 clear fuchsia ',
'bright blue  contain 3 striped gray , 2 dotted indigo , 5 clear magenta , 3 dotted green ',
'dotted red  contain 3 mirrored white ',
'light lime  contain 5 bright purple ',
'bright purple  contain 2 bright lavender , 1 clear turquoise , 3 pale magenta ',
'faded tomato  contain 2 shiny turquoise , 5 dim crimson ',
'light brown  contain 3 pale violet , 2 striped blue , 1 wavy lavender ',
'posh silver  contain 2 bright silver , 5 dim olive ',
'shiny chartreuse  contain 4 striped black ',
'dull violet  contain 1 striped white ',
'posh chartreuse  contain 5 wavy crimson , 1 vibrant orange , 2 mirrored tan , 5 shiny brown ',
'plaid green  contain 2 light aqua , 5 dull fuchsia ',
'pale bronze  contain 5 dull white ',
'muted violet  contain 3 pale red , 5 dull red , 5 light cyan ',
'wavy aqua  contain no other ',
'posh plum  contain 3 faded green ',
'wavy lavender  contain 1 light gold , 2 faded teal , 1 shiny tomato , 1 pale white ',
'dull silver  contain 5 mirrored indigo , 1 dim red , 2 shiny coral , 2 drab tan ',
'light teal  contain 4 bright lavender , 4 bright yellow , 5 wavy crimson ',
'shiny maroon  contain 2 clear magenta , 3 striped blue ',
'mirrored turquoise  contain 2 dark violet , 5 dark aqua ',
'light orange  contain 2 plaid lime ',
'dotted lavender  contain 1 striped olive ',
'posh magenta  contain 1 plaid teal , 1 muted salmon ',
'drab tan  contain 4 dull tan , 5 faded teal ',
'wavy olive  contain 5 plaid aqua , 3 dull turquoise , 5 faded aqua , 2 plaid maroon ',
'muted beige  contain 2 mirrored tomato , 4 dotted salmon ',
'muted chartreuse  contain 1 plaid white , 1 dull beige , 5 vibrant maroon , 3 drab gray ',
'striped teal  contain 4 wavy yellow , 1 dull lime , 1 pale green , 4 drab chartreuse ',
'pale green  contain 1 dim violet , 1 mirrored beige ',
'dim lime  contain 4 dotted aqua , 2 pale red ',
'clear purple  contain 5 clear lavender ',
'plaid beige  contain 1 bright olive , 1 light brown , 1 muted blue , 4 dotted green ',
'dark blue  contain 1 dim red , 2 wavy cyan ',
'shiny lime  contain 3 dull tomato , 2 bright gray , 1 pale fuchsia ',
'muted lavender  contain 2 mirrored tan , 1 vibrant orange , 2 light gold ',
'drab violet  contain 1 dotted beige , 5 faded purple , 1 pale green ',
'striped lime  contain 3 plaid orange ',
'posh gold  contain 3 dark bronze , 3 posh chartreuse , 1 clear lime , 5 shiny coral ',
'mirrored white  contain 4 dull red , 1 pale crimson , 2 posh blue ',
'dotted brown  contain 1 vibrant lavender , 3 dark lavender , 5 bright salmon ',
'faded salmon  contain 2 mirrored violet , 5 dark chartreuse , 5 dull silver , 1 mirrored teal ',
'dull purple  contain 2 light brown , 2 mirrored tan ',
'muted black  contain 4 vibrant indigo , 2 wavy crimson , 4 light cyan , 5 dim salmon ',
'muted cyan  contain 2 posh olive , 5 dark gray , 2 plaid green , 2 clear brown ',
'shiny violet  contain 1 vibrant gray , 4 posh teal ',
'dim lavender  contain 1 dim coral , 4 light silver , 3 dull teal , 3 wavy coral ',
'dotted tan  contain 5 plaid tan , 2 plaid plum , 3 vibrant crimson ',
'faded aqua  contain 3 light purple , 1 pale white , 5 muted turquoise ',
'drab coral  contain 4 vibrant turquoise , 1 dull yellow , 4 clear turquoise , 5 dull beige ',
'mirrored olive  contain 5 plaid magenta , 5 light indigo ',
'light salmon  contain 2 dull plum , 1 striped blue ',
'vibrant magenta  contain 5 muted lime , 3 dull tomato , 2 clear tomato , 3 dim brown ',
'dark brown  contain 4 dull gray ',
'striped plum  contain 2 plaid turquoise ',
'drab tomato  contain 1 mirrored black , 1 dull beige ',
'dotted black  contain 4 light cyan ',
'shiny plum  contain 5 drab magenta ',
'plaid purple  contain 1 dark black ',
'muted bronze  contain 4 muted white , 1 dotted bronze , 3 bright crimson ',
'striped aqua  contain 5 mirrored silver , 2 dim blue , 2 drab purple ',
'light indigo  contain 1 muted olive , 5 shiny plum ',
'drab lavender  contain 4 dotted aqua , 1 dull chartreuse , 5 drab teal , 3 light brown ',
'wavy fuchsia  contain 4 posh maroon ',
'dim blue  contain 2 mirrored purple , 2 dim gold , 3 vibrant chartreuse , 1 dull red ',
'muted olive  contain 2 pale crimson , 4 mirrored green , 1 dim white ',
'striped tomato  contain 4 posh tan , 2 pale crimson , 2 shiny fuchsia , 5 striped gray ',
'faded white  contain 3 vibrant tan ',
'dotted gold  contain 5 plaid gray , 5 mirrored cyan , 2 vibrant purple , 5 light orange ',
'vibrant crimson  contain 2 mirrored violet , 3 faded chartreuse , 3 wavy lavender ',
'light lavender  contain 2 light gold ',
'muted fuchsia  contain 4 drab blue ',
'clear tomato  contain 3 plaid aqua ',
'shiny fuchsia  contain 1 wavy lavender , 5 striped blue ',
'shiny cyan  contain 5 dim red , 3 dim brown ',
'wavy crimson  contain 3 bright lavender , 2 faded plum ',
'light cyan  contain 1 striped fuchsia ',
'mirrored crimson  contain 3 wavy lavender , 4 vibrant tan , 5 faded plum ',
'dark tomato  contain 5 mirrored gray , 5 muted fuchsia , 2 plaid lavender , 4 light purple ',
'plaid magenta  contain 1 muted silver , 5 light lavender , 4 muted brown , 3 drab turquoise ',
'vibrant olive  contain 1 plaid cyan , 5 drab white , 1 bright indigo , 5 plaid yellow ',
'dull crimson  contain 5 pale silver , 3 posh blue , 5 dull olive ',
'mirrored gray  contain 4 dull olive , 1 shiny fuchsia , 5 mirrored black , 2 clear magenta ',
'dim aqua  contain 3 mirrored indigo , 5 muted maroon , 4 dark orange ',
'bright tan  contain 2 bright teal , 5 vibrant indigo , 1 dull black ',
'dark white  contain 3 dark violet ',
'dull black  contain 5 posh cyan , 5 shiny tomato , 1 light yellow ',
'mirrored orange  contain 3 posh coral , 1 bright silver , 3 faded plum , 2 dotted coral ',
'mirrored tan  contain 2 pale violet , 1 dim gold , 2 faded green , 2 posh blue ',
'shiny turquoise  contain 1 vibrant silver ',
'plaid chartreuse  contain 4 striped white , 5 vibrant bronze , 1 pale brown ',
'mirrored plum  contain 1 shiny fuchsia , 4 bright indigo , 4 muted maroon , 2 drab red ',
'faded lavender  contain 3 faded chartreuse , 5 muted plum , 3 light brown ',
'dim green  contain 5 pale plum , 2 clear magenta ',
'bright green  contain 5 posh lime ',
'dim yellow  contain 1 plaid fuchsia , 1 dotted olive ',
'pale silver  contain 1 muted brown , 3 clear lavender ',
'dark turquoise  contain 2 wavy lavender , 4 posh gray , 3 plaid tan ',
'muted gray  contain 4 drab teal ',
'striped maroon  contain 1 striped fuchsia , 1 vibrant green ',
'clear crimson  contain 1 light black , 4 dim aqua , 2 dull red ',
'dotted bronze  contain 3 muted purple , 5 muted lime , 5 pale plum ',
'wavy coral  contain 1 dull white ',
'dotted purple  contain 2 dim blue ',
'pale cyan  contain 1 dark beige , 1 drab crimson , 2 plaid black , 3 dim tomato ',
'clear green  contain 4 muted lime , 1 mirrored white , 4 pale lavender , 2 muted gold ',
'plaid yellow  contain 3 muted silver ',
'pale tan  contain 4 shiny cyan ',
'clear brown  contain 2 dull maroon , 4 posh orange , 3 mirrored blue ',
'striped cyan  contain 1 muted tomato , 2 dim magenta ',
'clear lavender  contain 3 plaid fuchsia ',
'dull gold  contain 5 dim salmon ',
'dark cyan  contain 4 pale gold , 2 muted tan ',
'plaid olive  contain 5 posh tan ',
'vibrant aqua  contain 3 striped violet , 3 muted turquoise ',
'dim white  contain 2 plaid fuchsia , 1 dull olive , 4 faded teal ',
'mirrored silver  contain 2 mirrored gray , 4 muted blue , 4 dull gray ',
'wavy violet  contain 5 bright green , 3 pale silver , 5 dark aqua , 4 shiny tomato ',
'bright coral  contain 2 striped chartreuse , 4 clear aqua , 5 vibrant olive , 3 wavy tomato ',
'plaid coral  contain 3 clear turquoise , 2 muted olive , 2 faded crimson , 5 dull yellow ',
'posh purple  contain 4 dull cyan ',
'muted maroon  contain 5 striped white , 2 pale blue , 3 dull crimson , 1 pale lavender ',
'mirrored black  contain 5 plaid fuchsia , 3 vibrant green , 1 faded chartreuse ',
'vibrant turquoise  contain 4 plaid black , 1 shiny brown , 5 wavy purple , 2 dim red ',
'muted gold  contain 3 clear lavender , 2 dotted chartreuse , 3 dim green , 2 mirrored black ',
'dark lime  contain 5 dark aqua , 2 plaid plum ',
'posh brown  contain 3 drab fuchsia , 1 dim gold , 4 drab magenta , 3 wavy aqua ',
'clear yellow  contain 3 wavy indigo ',
'muted blue  contain 1 wavy crimson , 5 mirrored red , 5 shiny crimson , 4 plaid fuchsia ',
'drab white  contain 5 dull olive , 2 posh maroon , 2 pale silver , 5 muted brown ',
'dim gold  contain no other ',
'faded plum  contain 4 plaid turquoise , 5 drab chartreuse , 2 dotted olive , 3 plaid fuchsia ',
'light blue  contain 4 plaid coral , 5 dotted violet ',
'vibrant gold  contain 2 dim fuchsia , 3 faded white ',
'plaid crimson  contain 1 plaid plum ',
'dim fuchsia  contain 3 faded teal ',
'mirrored chartreuse  contain 3 wavy black ',
'mirrored fuchsia  contain 1 faded teal , 5 light coral ',
'muted coral  contain 3 light magenta , 5 faded green , 1 dull olive , 2 muted silver ',
'dim teal  contain 4 pale teal , 1 plaid maroon , 2 plaid yellow , 1 plaid orange ',
'faded green  contain 4 striped gray ',
'vibrant beige  contain 2 muted blue , 3 vibrant gray ',
'muted silver  contain 3 dotted violet ',
'dotted cyan  contain 2 mirrored gray , 5 muted purple , 2 faded bronze ',
'bright turquoise  contain 1 pale tan , 1 pale salmon ',
'wavy gold  contain 2 pale olive ',
'faded turquoise  contain 2 vibrant fuchsia , 2 drab fuchsia , 4 striped black ',
'faded lime  contain 4 dim gold , 5 vibrant yellow ',
'faded black  contain 2 dark coral , 2 shiny crimson , 4 clear gray ',
'vibrant silver  contain 1 shiny teal , 5 dotted chartreuse , 1 pale magenta , 3 clear coral ',
'dim brown  contain 1 posh gray ',
'dim cyan  contain 2 drab tan , 4 posh white ',
'bright fuchsia  contain 1 dark crimson , 3 posh coral ',
'clear tan  contain 1 light tomato , 5 bright olive , 1 dull violet , 2 bright green ',
'pale red  contain 5 mirrored tomato , 4 dull red , 3 shiny teal ',
'drab chartreuse  contain 1 vibrant green , 3 shiny crimson , 3 dotted olive ',
'dark gray  contain 4 dotted coral , 2 shiny teal , 1 muted blue , 4 bright silver ',
'dim purple  contain 5 dotted gold ',
'shiny crimson  contain no other ',
'posh maroon  contain 4 light magenta , 4 muted tan ',
'mirrored purple  contain no other ',
'wavy silver  contain 5 faded lavender , 4 clear lime ',
'dark indigo  contain 3 light plum , 5 dotted crimson , 1 wavy plum , 4 light gold ',
'wavy gray  contain 3 clear gold ',
'pale gray  contain 2 bright gold ',
'muted turquoise  contain 1 wavy bronze , 1 muted blue ',
'dull yellow  contain 3 posh olive , 5 faded red ',
'mirrored tomato  contain 3 striped olive , 4 light chartreuse , 5 pale silver ',
'dotted crimson  contain 3 muted brown , 4 dim blue , 4 dark silver , 3 pale lavender ',
'pale magenta  contain 3 clear bronze , 1 plaid brown , 1 dim gold ',
'faded brown  contain 3 plaid fuchsia , 1 faded chartreuse ',
'clear salmon  contain 1 plaid fuchsia , 4 wavy coral , 5 shiny coral , 3 clear turquoise ',
'clear coral  contain 5 faded chartreuse , 1 drab chartreuse , 2 dim gold ',
'dull magenta  contain 2 dark coral , 4 drab indigo , 3 posh maroon ',
'posh black  contain 4 dim white , 2 dark lime , 5 faded green , 2 plaid green ',
'dim beige  contain 2 striped lavender , 5 posh lavender ',
'clear turquoise  contain 2 muted brown ',
'faded red  contain 2 vibrant salmon , 3 dark orange ',
'shiny aqua  contain 1 shiny salmon , 2 light olive , 4 dotted magenta ',
'dotted yellow  contain 3 striped green , 5 posh tan ',
'dark silver  contain 4 posh maroon , 4 clear lavender ',
'dull gray  contain 3 plaid violet , 3 dark silver , 3 mirrored black , 1 drab indigo ',
'drab indigo  contain 2 faded plum , 4 clear turquoise , 2 pale white , 3 drab magenta ',
'dotted indigo  contain 1 dim olive ',
'drab crimson  contain 3 plaid turquoise , 2 pale purple ',
'pale coral  contain 3 posh blue ',
'shiny tomato  contain 5 muted salmon , 4 faded plum , 1 drab chartreuse , 5 muted brown ',
'wavy yellow  contain 4 striped black , 1 dull turquoise ',
'faded indigo  contain 4 wavy crimson , 1 dark orange , 5 dotted coral ',
'light white  contain 2 bright blue , 3 pale lavender , 3 dull lime , 2 pale coral ',
'dark black  contain 4 light orange , 5 shiny coral ',
'dull white  contain 3 striped fuchsia ',
'bright tomato  contain 5 shiny cyan , 4 plaid bronze , 1 muted salmon ',
'vibrant lime  contain 1 dotted gray , 3 drab crimson , 3 faded crimson ',
'dotted orange  contain 2 dark purple , 4 faded lavender ',
'dim black  contain 3 dark turquoise , 5 posh gray , 4 dull tan ',
'light bronze  contain 1 striped blue ',
'dotted salmon  contain 3 muted crimson , 1 faded gold , 1 wavy violet , 3 striped gray ',
'shiny coral  contain 1 shiny fuchsia ',
'clear beige  contain 1 dim yellow , 3 mirrored tomato ',
'mirrored blue  contain 1 plaid fuchsia ',
'bright yellow  contain 3 dotted violet , 5 dull teal ',
'drab bronze  contain 1 dim black , 5 faded indigo ',
'posh red  contain 1 pale silver ',
'dark bronze  contain 4 dotted fuchsia , 5 light salmon , 1 muted brown , 1 posh blue ',
'pale indigo  contain 4 vibrant bronze ',
'light violet  contain 2 shiny tomato , 1 wavy maroon ',
'muted crimson  contain 4 clear gold , 4 dark coral ',
'faded chartreuse  contain no other ',
'muted tan  contain no other ',
'clear lime  contain 1 bright lavender , 4 dim olive , 4 pale plum ',
'plaid lime  contain 1 drab lime ',
'mirrored green  contain 4 dim tomato , 3 clear coral , 2 shiny lavender ',
'bright orange  contain 5 bright salmon , 4 plaid maroon ',
'dim plum  contain 1 striped chartreuse , 3 dotted violet , 1 faded teal , 1 dim green ',
'faded tan  contain 4 mirrored black ',
'wavy salmon  contain 1 faded tomato ',
'dim coral  contain 3 dull indigo , 3 wavy tomato ',
'dim turquoise  contain 2 wavy yellow , 4 dull silver ',
'dull chartreuse  contain 5 mirrored purple , 4 pale coral , 2 shiny purple ',
'drab fuchsia  contain 4 dotted olive , 2 dim gold , 4 shiny crimson ',
'dull tomato  contain 2 striped indigo ',
'striped lavender  contain 5 plaid cyan , 5 faded green , 1 posh gray ',
'clear gold  contain 5 clear turquoise , 2 dull tan ',
'dark orange  contain 5 dotted olive , 3 pale magenta , 2 posh blue , 1 vibrant green ',
'clear plum  contain 4 posh olive ',
'dark olive  contain 5 faded silver , 1 vibrant tan , 3 bright crimson ',
'striped magenta  contain 3 shiny lavender , 5 faded green , 4 striped lavender , 2 mirrored black ',
'dim chartreuse  contain 4 striped turquoise , 5 mirrored tomato ',
'faded teal  contain 3 dull olive , 1 dull tan , 5 posh maroon ',
'wavy cyan  contain 1 shiny magenta ',
'dim tomato  contain 1 plaid plum , 2 plaid fuchsia , 5 mirrored blue ',
'drab maroon  contain 4 faded coral , 2 dotted black , 3 posh orange , 2 faded indigo ',
'posh white  contain 2 clear coral , 3 plaid turquoise , 2 mirrored black ',
'shiny orange  contain 4 light coral ',
'bright teal  contain 3 clear gray , 2 clear turquoise , 3 faded crimson ',
'clear aqua  contain 3 muted silver , 5 dim white , 5 drab lime , 4 clear gold ',
'vibrant black  contain 1 dim violet , 5 pale indigo , 4 wavy indigo , 5 muted green ',
'clear chartreuse  contain 1 dull black , 3 dotted olive , 3 dull indigo ',
'posh lavender  contain 5 vibrant orange , 2 dim white , 1 dull beige ',
'dark crimson  contain 5 faded tomato , 1 striped fuchsia ',
'light black  contain 3 muted tomato , 5 clear bronze , 4 drab chartreuse ',
'wavy plum  contain 3 dotted coral , 5 vibrant olive ',
'plaid salmon  contain 4 dull salmon ',
'wavy chartreuse  contain 1 mirrored turquoise ',
'vibrant fuchsia  contain 2 mirrored gold , 5 dull bronze ',
'dim violet  contain 1 faded fuchsia , 1 mirrored red , 2 posh fuchsia , 4 mirrored turquoise ',
'vibrant tan  contain 2 clear salmon , 5 drab red , 3 dotted gray ',
'dim bronze  contain 1 drab green ',
'shiny lavender  contain 3 muted salmon ',
'striped fuchsia  contain 4 dim gold , 2 dotted crimson ',
'dim tan  contain 2 plaid red , 2 bright chartreuse , 2 dim salmon ',
'dotted violet  contain no other ',
'dull maroon  contain 4 faded chartreuse ',
'clear violet  contain 1 drab lime , 5 muted coral , 1 clear lavender ',
'plaid maroon  contain 1 drab red , 3 muted gold ',
'vibrant gray  contain 1 plaid fuchsia ',
'light yellow  contain 4 mirrored blue , 2 plaid fuchsia , 1 wavy tomato ',
'dotted teal  contain 3 light tan ',
'vibrant chartreuse  contain 1 shiny crimson , 2 plaid fuchsia ',
'dull lavender  contain 1 light crimson ',
'dark gold  contain 3 muted olive , 1 posh tan , 5 vibrant purple ',
'light aqua  contain 1 wavy bronze ',
'dim crimson  contain 3 plaid beige , 1 plaid yellow ',
'plaid brown  contain 5 dotted olive , 4 muted salmon , 3 dim gold ',
'dotted magenta  contain 1 wavy coral , 2 drab turquoise , 5 mirrored tomato ',
'muted tomato  contain 4 wavy fuchsia , 4 pale magenta ',
'posh tomato  contain 1 striped beige , 1 faded brown ',
'faded gray  contain 4 plaid maroon , 5 muted silver , 5 muted maroon , 4 vibrant fuchsia ',
'plaid lavender  contain 3 dim blue , 4 vibrant gray , 2 light silver , 1 dull green ',
'muted indigo  contain 2 dark coral , 1 vibrant indigo , 3 dim yellow , 4 muted aqua ',
'posh turquoise  contain 4 drab red , 2 faded teal , 4 dull maroon ',
'bright red  contain 5 wavy lime , 4 bright black , 1 muted white ',
'pale tomato  contain 1 posh olive ',
'dim maroon  contain 5 vibrant red , 3 vibrant orange , 1 dark chartreuse ',
'shiny teal  contain 2 plaid fuchsia , 4 dotted olive , 2 vibrant chartreuse , 4 muted brown ',
'plaid gold  contain 3 clear olive , 1 faded chartreuse ',
'shiny beige  contain 5 wavy lavender , 3 muted salmon ',
'drab green  contain 1 clear bronze , 2 posh teal , 1 dotted green , 5 pale white ',
'light beige  contain 5 vibrant red ',
'clear indigo  contain 4 plaid violet ',
'clear black  contain 5 striped olive , 5 posh red , 4 posh brown , 4 shiny olive ',
'wavy red  contain 1 dull red , 2 shiny magenta , 4 shiny black ',
'striped indigo  contain 1 striped black , 2 plaid cyan ',
'clear bronze  contain no other ',
'shiny salmon  contain 1 muted tan , 5 striped white , 5 striped fuchsia ',
'mirrored teal  contain 5 light lime ',
'dotted blue  contain 4 dark aqua , 3 clear bronze , 4 dull olive ',
'shiny blue  contain 3 bright green , 5 pale lavender ',
'faded cyan  contain 3 dark red , 4 drab cyan , 5 faded beige ',
'light purple  contain 3 posh silver ',
'vibrant teal  contain 4 dotted gold , 1 plaid yellow , 1 mirrored cyan , 5 dull indigo ',
'wavy bronze  contain 2 muted silver ',
'dim red  contain 3 clear bronze , 5 faded plum ',
'muted yellow  contain 2 muted blue , 5 striped beige , 2 drab indigo , 5 drab red ',
'mirrored lavender  contain 3 dull maroon ',
'pale white  contain 3 vibrant chartreuse , 5 posh maroon , 4 muted brown , 3 plaid turquoise ',
'vibrant maroon  contain 2 shiny purple , 2 dim yellow ',
'dull teal  contain 2 mirrored black , 5 drab white ',
'bright olive  contain 5 clear bronze , 2 drab red ',
'shiny white  contain 2 clear brown , 4 muted white ',
'muted aqua  contain 4 dim green , 3 shiny tomato , 2 posh chartreuse , 4 muted lavender ',
'dull fuchsia  contain 5 mirrored red , 4 dark lime ',
'pale brown  contain 4 striped indigo , 4 dotted coral , 4 shiny maroon , 5 striped white ',
'plaid tomato  contain 4 drab turquoise , 1 posh plum , 5 dotted indigo ',
'pale teal  contain 5 dull plum , 5 dim crimson , 5 shiny purple ',
'mirrored yellow  contain 1 posh olive ',
'dim silver  contain 4 clear magenta , 3 plaid silver , 1 striped maroon ',
'posh cyan  contain 5 pale coral , 2 faded magenta , 4 dim cyan ',
'clear silver  contain 1 muted red , 1 faded turquoise ',
'shiny black  contain 1 dim blue ',
'bright silver  contain 4 shiny teal , 1 dull red , 4 bright olive , 2 shiny brown ',
'drab aqua  contain 3 vibrant indigo , 5 wavy cyan , 3 shiny violet , 2 dull bronze ',
'vibrant lavender  contain 1 muted turquoise , 5 light crimson , 3 wavy crimson ',
'pale lavender  contain 2 posh blue , 5 dim red ',
'plaid black  contain 2 faded green , 1 bright black ',
'dotted white  contain 5 shiny gold , 2 dotted magenta ',
'wavy maroon  contain 3 striped white , 3 mirrored black , 3 plaid turquoise ',
'dotted plum  contain 1 faded coral ',
'striped salmon  contain 4 plaid indigo , 1 light brown , 4 posh tomato , 1 bright chartreuse ',
'faded violet  contain 5 shiny coral ',
'dotted fuchsia  contain 3 dim red , 1 muted purple , 3 striped indigo , 3 drab magenta ',
'dark coral  contain 4 pale lavender , 2 posh coral , 5 striped olive , 1 clear bronze ',
'posh tan  contain 2 dark silver ',
'dotted green  contain 3 drab white , 4 drab red , 4 pale magenta ',
'clear blue  contain 2 plaid fuchsia , 2 dotted purple , 2 faded violet , 1 dim blue ',
'dotted olive  contain 3 plaid fuchsia , 2 dim gold , 1 shiny crimson , 2 muted tan ',
'plaid red  contain 3 dull violet , 1 dotted crimson , 1 dull plum ',
'plaid teal  contain 4 muted tomato , 5 posh tan ',
'striped green  contain 5 dotted gray , 1 faded green , 1 muted brown ',
'pale gold  contain 4 shiny purple , 2 dim cyan ',
'dim salmon  contain 3 bright green , 2 dim magenta , 1 dim black ',
'drab beige  contain 3 light lime , 2 faded teal , 3 light fuchsia ',
'shiny green  contain 5 wavy gray , 1 mirrored tan ',
'dark red  contain 4 mirrored silver , 5 pale plum , 1 wavy violet ',
'wavy black  contain 1 drab white , 4 shiny chartreuse , 2 striped white ',
'vibrant white  contain 5 shiny lavender , 4 dark black , 1 dull bronze ',
'faded silver  contain 3 vibrant purple , 5 mirrored blue , 5 dull chartreuse , 1 faded bronze ',
'mirrored brown  contain 5 dull plum , 3 mirrored orange , 1 light gold , 5 light cyan ',
'striped brown  contain 4 muted indigo , 3 dim coral , 3 drab turquoise ',
'faded beige  contain 1 drab chartreuse , 5 faded fuchsia , 1 clear salmon , 2 dim cyan ',
'pale salmon  contain 1 dotted tomato , 5 faded silver , 2 dim beige ',
'striped chartreuse  contain 1 light magenta ',
'pale chartreuse  contain 3 dark white , 5 shiny aqua ',
'wavy teal  contain 2 light orange , 3 dull cyan ',
'dull tan  contain 3 mirrored purple , 5 plaid turquoise , 5 posh blue , 5 shiny crimson ',
'wavy white  contain 5 wavy olive ',
'clear magenta  contain 1 pale lavender ',
'light gold  contain 1 posh maroon , 1 dull olive , 3 striped chartreuse ',
'striped olive  contain 4 clear magenta , 3 clear gold , 3 shiny black ',
'plaid aqua  contain 5 posh tan , 4 mirrored indigo , 3 drab white , 1 drab red ',
'dark maroon  contain 4 dim purple , 5 dark turquoise ',
'mirrored magenta  contain 3 striped lime , 4 posh lime , 2 shiny olive ',
'bright brown  contain 5 dim yellow ',
'bright black  contain 4 posh brown , 3 shiny beige , 2 wavy lavender ',
'light olive  contain 1 dark purple , 2 clear fuchsia , 2 striped blue , 4 pale brown ',
'dull beige  contain 5 shiny fuchsia , 4 muted brown , 5 posh gray , 4 posh maroon ',
'bright indigo  contain 5 dotted coral , 2 dull red , 5 dotted olive ',
'drab cyan  contain 1 mirrored brown , 4 dim aqua , 4 mirrored plum ',
'faded magenta  contain 2 dull silver , 3 clear gold ',
'pale aqua  contain 1 bright indigo , 2 posh maroon , 1 pale lavender ',
'light red  contain 3 muted magenta , 4 pale olive ',
'vibrant salmon  contain 3 dim tomato , 1 vibrant lavender , 4 muted plum ',
'striped blue  contain 1 dull tan , 3 muted silver , 2 dotted green ',
'shiny olive  contain 1 plaid cyan , 5 dark violet , 3 clear bronze ',
'drab black  contain 1 faded black ',
'posh bronze  contain 5 plaid brown , 1 striped white ',
'posh blue  contain 3 plaid fuchsia , 1 muted silver , 1 drab chartreuse ',
'posh fuchsia  contain 5 plaid red , 5 vibrant silver , 4 faded coral ',
'clear olive  contain 1 plaid orange , 5 dim cyan ',
'striped red  contain 3 clear crimson , 5 clear lime , 4 faded bronze , 2 posh teal ',
'dotted coral  contain 2 pale silver ',
'drab teal  contain 2 pale violet , 1 mirrored red ',
'pale black  contain 5 dull olive ',
'vibrant brown  contain 1 mirrored indigo , 3 clear white ',
'pale olive  contain 1 pale white , 1 dark plum , 1 dim tomato , 1 vibrant beige ',
'faded orange  contain 1 striped coral , 3 dull plum , 3 drab silver , 3 clear fuchsia ',
'plaid silver  contain 3 drab chartreuse ',
'pale beige  contain 5 clear yellow , 2 vibrant purple , 1 faded salmon ',
'dark magenta  contain 2 wavy lavender , 4 shiny tomato , 2 faded plum ',
'dark purple  contain 2 clear brown , 1 vibrant chartreuse , 1 vibrant fuchsia , 5 pale blue ',
'vibrant yellow  contain 5 drab chartreuse ',
'light silver  contain 5 shiny crimson ',
'clear maroon  contain 2 plaid teal , 4 muted tomato , 3 faded tan ',
'drab turquoise  contain 1 plaid yellow , 4 wavy bronze , 3 vibrant olive ',
'drab salmon  contain 1 dark white , 3 light plum , 3 posh silver , 3 clear salmon ',
'shiny magenta  contain 1 striped chartreuse ',
'dull indigo  contain 2 striped green ',
'posh green  contain 4 muted gold , 2 light chartreuse ',
'striped crimson  contain 5 striped turquoise ',
'posh aqua  contain 5 light magenta ',
'vibrant bronze  contain 4 pale magenta , 4 light silver , 2 vibrant yellow , 2 wavy yellow ',
'bright bronze  contain 3 dark violet , 1 dim black , 2 dark silver ',
'plaid orange  contain 3 dim tomato , 3 drab turquoise ',
'drab lime  contain 1 drab white , 5 muted white ',
'bright lime  contain 5 shiny teal , 3 muted purple ',
'wavy lime  contain 5 dull maroon ',
'dim indigo  contain 4 pale cyan , 2 dotted turquoise , 2 striped blue , 2 posh brown ',
'wavy blue  contain 2 pale plum ',
'muted brown  contain 1 muted silver , 1 dotted olive , 1 drab fuchsia ',
'shiny bronze  contain 2 dotted gray , 2 shiny magenta , 4 posh black ',
'light fuchsia  contain 3 mirrored brown , 1 faded purple , 2 wavy violet , 1 posh salmon ',
'light maroon  contain 4 dull chartreuse , 4 dotted cyan , 2 muted tan ',
'muted teal  contain 2 muted coral , 1 dotted aqua , 2 vibrant gray , 5 dim crimson ',
'shiny yellow  contain 4 bright olive ',
'bright maroon  contain 2 clear maroon , 2 striped cyan ',
'pale crimson  contain 1 posh blue , 4 posh maroon , 2 clear lavender ',
'dim orange  contain 5 striped fuchsia , 3 posh tan , 1 striped beige ',
'vibrant green  contain 3 dotted violet , 2 shiny crimson , 1 clear lavender ',
'striped orange  contain 3 bright white , 2 dotted maroon , 5 drab indigo ',
'dull plum  contain 1 striped fuchsia , 3 faded crimson , 3 dim green , 2 posh lavender ',
'drab olive  contain 2 posh white , 3 bright salmon ',
'dull green  contain 5 wavy turquoise , 4 mirrored gray , 3 light maroon ',
'mirrored cyan  contain 1 plaid beige ',
'plaid cyan  contain 5 faded chartreuse , 5 shiny crimson , 3 drab fuchsia , 4 wavy aqua ',
'posh yellow  contain 5 dark chartreuse ',
'clear orange  contain 3 bright green , 4 shiny gold ',
'dim magenta  contain 5 faded crimson , 3 plaid tan , 5 mirrored orange , 1 pale lavender ',
'bright beige  contain 4 bright gold , 5 pale chartreuse ',
'dark plum  contain 2 pale silver ',
'bright violet  contain 1 dotted green ',
'vibrant cyan  contain 1 dark turquoise ',
'posh gray  contain 3 pale crimson , 3 muted white , 4 shiny brown , 3 clear magenta ',
'striped beige  contain 5 dull bronze , 4 dim blue , 1 dotted olive ',
'shiny gold  contain 5 vibrant green , 4 pale violet , 4 dull olive , 3 pale white ',
'dark salmon  contain 3 muted bronze , 4 muted silver , 2 pale purple ',
'wavy tan  contain 3 light turquoise , 5 dark bronze ',
'light plum  contain 5 wavy bronze , 4 dull crimson , 5 dim aqua ',
'drab silver  contain 2 dim fuchsia , 3 wavy bronze ',
'plaid indigo  contain 3 plaid tomato , 5 clear beige ',
'pale lime  contain 2 striped cyan , 2 mirrored lavender ',
'faded gold  contain 4 faded tomato , 2 light cyan , 2 pale orange , 1 wavy bronze ',
'striped tan  contain 1 bright silver , 2 faded green , 5 dim blue , 1 shiny maroon ',
'drab purple  contain 3 dull red , 3 light olive , 3 shiny red ',
'muted orange  contain 1 mirrored brown , 2 muted green ',
'dull brown  contain 3 dim silver , 4 posh lavender , 5 dark white ',
'wavy tomato  contain 1 drab lime , 1 shiny teal , 5 dotted violet , 4 light crimson ',
'dark green  contain 2 posh orange , 4 mirrored tan , 5 mirrored violet ',
'wavy turquoise  contain 4 light salmon , 2 shiny maroon , 1 muted salmon ',
'posh orange  contain 5 dull red , 1 drab lime , 2 shiny gold ',
'vibrant indigo  contain 5 dark violet ',
'faded fuchsia  contain 5 clear lavender , 1 dull silver , 5 drab lime , 3 bright white ',
'wavy beige  contain 3 vibrant green , 3 faded teal , 4 muted indigo ',
'pale fuchsia  contain 1 drab lime ',
'muted salmon  contain 1 dotted violet , 4 vibrant chartreuse , 3 muted silver ',
'shiny red  contain 2 dull gray , 3 pale white , 1 faded brown ',
'clear gray  contain 1 posh maroon , 1 shiny beige ',
'muted green  contain 1 drab magenta , 3 pale fuchsia , 5 dark fuchsia , 1 dull gray ',
'vibrant purple  contain 1 vibrant yellow , 4 muted aqua ',
'dark fuchsia  contain 5 mirrored lavender , 2 dim red , 5 shiny teal , 5 vibrant beige ',
'striped purple  contain 2 dim aqua , 1 posh teal , 5 pale brown ',
'posh lime  contain 2 wavy aqua ',
'striped violet  contain 2 dotted chartreuse ',
'muted lime  contain 1 shiny brown , 2 bright purple , 2 drab chartreuse , 4 clear lavender ',
'light gray  contain 5 dull maroon , 4 dull crimson , 5 mirrored cyan ',
'mirrored maroon  contain 1 mirrored chartreuse , 1 muted cyan ',
'light turquoise  contain 2 bright yellow ',
'vibrant blue  contain 4 muted tomato , 2 dull salmon ',
'mirrored indigo  contain 3 light chartreuse , 5 dark turquoise ',
'faded bronze  contain 5 dotted chartreuse ',
'dotted beige  contain 4 bright purple , 2 striped green , 3 posh brown ',
'drab red  contain 2 vibrant chartreuse , 1 dim red , 4 dark silver , 4 pale magenta ',
'wavy orange  contain 3 striped bronze , 4 dotted tan ',
'striped black  contain 1 shiny tomato ',
'drab gold  contain 1 plaid lime , 2 wavy lavender ',
'shiny brown  contain 5 dull tan ',
'posh beige  contain 1 drab gold , 3 dull beige , 1 posh blue , 2 drab red ',
'light green  contain 3 mirrored tan ',
'mirrored coral  contain 5 mirrored lavender , 5 dark white , 5 pale silver ',
'plaid bronze  contain 3 pale lavender , 1 muted silver , 2 faded teal , 1 dull teal ',
'light chartreuse  contain 1 muted blue , 4 posh chartreuse , 2 wavy aqua , 4 vibrant orange ',
'drab yellow  contain 2 shiny aqua ',
'plaid turquoise  contain no other ',
'drab orange  contain 1 posh salmon , 5 dark violet ',
'dark teal  contain 4 bright indigo , 3 plaid coral , 1 dark violet , 5 shiny tomato ',
'drab gray  contain 4 dotted maroon ',
'dotted maroon  contain 4 plaid turquoise , 5 pale bronze ',
'muted red  contain 5 posh brown ',
'dim olive  contain 3 posh brown , 2 faded plum , 4 wavy tomato ',
'pale maroon  contain 5 dark gold , 3 dotted silver , 3 shiny tomato ',
'dotted turquoise  contain 1 plaid blue , 5 dim green , 5 dull plum ',
'dotted tomato  contain 2 dotted indigo , 2 clear fuchsia ',
'dark aqua  contain 5 posh olive ',
'dark tan  contain 5 dotted chartreuse , 5 posh red , 3 plaid cyan , 5 pale plum ',
'bright chartreuse  contain 4 posh white , 4 shiny maroon , 1 shiny tomato ',
'striped gray  contain 4 shiny gold , 3 drab white , 3 plaid cyan ',
'dull olive  contain 4 plaid brown , 2 plaid turquoise , 2 plaid cyan , 1 vibrant green ',
'shiny indigo  contain 3 shiny black , 1 dark orange , 1 posh white ',
'bright lavender  contain 1 muted salmon , 5 posh maroon ',
'plaid white  contain 5 wavy silver ',
'light coral  contain 3 pale silver ',
'plaid plum  contain 4 shiny brown , 1 dark silver , 4 pale lavender ',
'light magenta  contain 5 drab chartreuse ',
'shiny tan  contain 4 vibrant chartreuse , 5 dim brown ',
'wavy magenta  contain 1 vibrant turquoise , 4 dull violet , 5 clear indigo ',
'pale blue  contain 2 posh lime , 1 shiny brown ',
'dull orange  contain 5 dull lime , 1 pale crimson ',
'striped white  contain 1 posh aqua , 3 pale magenta , 2 posh gray ',
'dotted aqua  contain 2 plaid teal ',
'wavy indigo  contain 4 dark blue , 3 dotted black , 2 pale violet , 4 pale silver ',
'bright plum  contain 3 muted green ',
'bright gold  contain 3 dull beige , 3 faded plum , 1 mirrored gray , 5 muted lime ',
'clear fuchsia  contain 3 clear orange , 5 dull crimson , 3 drab red , 5 vibrant silver ',
'posh olive  contain 2 vibrant green ',
'faded maroon  contain 2 vibrant chartreuse , 5 drab tomato , 3 dim tomato ',
'posh violet  contain 1 dim gold , 2 light chartreuse , 4 faded indigo , 2 plaid violet ',
'drab blue  contain 4 muted purple , 5 bright olive ',
'dull turquoise  contain 5 pale lavender , 3 light aqua , 3 drab teal ',
'striped silver  contain 4 wavy black , 5 plaid magenta ',
'striped gold  contain 3 shiny tomato , 2 light fuchsia , 1 bright salmon ',
'mirrored violet  contain 4 mirrored blue ',
'vibrant red  contain 4 striped lavender , 1 clear fuchsia ',
'striped yellow  contain 3 vibrant red ',
'dotted silver  contain 1 muted blue , 3 shiny teal , 2 plaid coral , 1 dim aqua'
] 

// On formate les données format {color: [color: number, ...], ...}

const color_raw_obj = {}

for (const colorString of input) {
    const [key, contain_raw] = colorString.split('contain')

    const contain = contain_raw.split(',').reduce((acc,x) => {
        if (x.trim() !== 'no other') {
            const [number, color1, color2] = x.trim().split(' ')
            acc[`${color1.trim()} ${color2.trim()}`] = parseInt(number.trim())
        }
        return acc
    }, {})
    color_raw_obj[key.trim()] = contain
}

console.dir(color_raw_obj, {depth: null})